In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import os

In [4]:
%matplotlib inline

In [5]:
feature_file= os.path.abspath('features_NORG.csv')
feature_df = pd.read_csv(feature_file,index_col=False)
feature_df.head(4)

0         1         2         3         4         5         6  \
0  0.279514  0.703756  0.736823  0.806092  0.782010  0.713422  0.656320   
1  0.287760  0.748217  0.821957  0.812205  0.735090  0.664197  0.637912   
2  0.277091  0.781108  0.860907  0.803445  0.767308  0.686528  0.623064   
3  0.326421  0.772341  0.855526  0.841515  0.820705  0.762666  0.705555   

          7         8         9  ...       153       154       155       156  \
0  0.633494  0.670024  0.731536  ...  0.000002  0.000003  0.000003  0.000003   
1  0.617599  0.715936  0.740380  ...  0.000014  0.000017  0.000017  0.000017   
2  0.616170  0.673181  0.728865  ...  0.000004  0.000004  0.000005  0.000005   
3  0.690831  0.707719  0.751362  ...  0.000039  0.000042  0.000041  0.000044   

        157       158       159       160           161   labels  
0  0.000003  0.000003  0.000002  0.000001  5.983615e-08  neutral  
1  0.000019  0.000018  0.000014  0.000005  3.123728e-07  neutral  
2  0.000006  0.000008  0.000008  0.000003  1.024004e-07  neutral  
3  0.000047  0.000047  0.000038  0.000013  8.357285e-07  neutral  

[4 rows x 163 columns]

In [6]:
X = feature_df.iloc[: ,:-1].values
Y = feature_df['labels'].values
X,Y

(array([[2.79513889e-01, 7.03756313e-01, 7.36823361e-01, ...,
         2.47309882e-06, 1.09128795e-06, 5.98361512e-08],
        [2.87760417e-01, 7.48216598e-01, 8.21957068e-01, ...,
         1.35066299e-05, 4.73744792e-06, 3.12372779e-07],
        [2.77090567e-01, 7.81108419e-01, 8.60906722e-01, ...,
         8.40919185e-06, 3.07295710e-06, 1.02400419e-07],
        ...,
        [2.09968171e-01, 6.55012106e-01, 7.10416982e-01, ...,
         7.14321749e-05, 3.26904090e-05, 2.47032433e-06],
        [3.01945891e-01, 6.69872168e-01, 6.64390940e-01, ...,
         1.48608312e-03, 4.03538120e-04, 3.17646428e-05],
        [2.89492911e-01, 7.00357582e-01, 6.78360979e-01, ...,
         5.37185735e-04, 1.83013655e-04, 1.11069563e-05]]),
 array(['neutral', 'neutral', 'neutral', ..., 'surprised', 'surprised',
        'surprised'], dtype=object))

In [7]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder,LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import sys

import warnings
if not sys.warnoptions:
    warnings.simplefilter("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [8]:
X.shape,Y.shape

((1440, 162), (1440,))

In [9]:
OHE = OneHotEncoder()
Scaler = StandardScaler()
Y = OHE.fit_transform(Y.reshape(-1,1)).toarray()
X = Scaler.fit_transform(X)

In [10]:
# making our data compatible to model.
x_test = np.expand_dims(X, axis=2)

x_test, Y

(array([[[ 0.823544  ],
         [ 0.4866303 ],
         [ 0.7864489 ],
         ...,
         [-0.37586158],
         [-0.37585281],
         [-0.37453239]],
 
        [[ 1.03818771],
         [ 1.09555119],
         [ 1.82215654],
         ...,
         [-0.36679221],
         [-0.36677749],
         [-0.36545267]],
 
        [[ 0.76046887],
         [ 1.54603227],
         [ 2.29600475],
         ...,
         [-0.37098222],
         [-0.37092042],
         [-0.37300203]],
 
        ...,
 
        [[-0.98661796],
         [-0.18096249],
         [ 0.46519789],
         ...,
         [-0.31917845],
         [-0.29720242],
         [-0.28786553]],
 
        [[ 1.40741254],
         [ 0.02255852],
         [-0.09473924],
         ...,
         [ 0.8436395 ],
         [ 0.6258396 ],
         [ 0.76538434]],
 
        [[ 1.08328171],
         [ 0.44008183],
         [ 0.0752155 ],
         ...,
         [ 0.06366271],
         [ 0.07695298],
         [ 0.02265651]]]),
 array([[0., 0., 0.

In [11]:
from tensorflow.keras.models import load_model

In [12]:
model_1_path = os.path.abspath(os.path.join('Models','Model_osp_3_83.h5'))
model_2_path = os.path.abspath(os.path.join('Models','Model_osp_4_84.25.h5'))
model_3_path = os.path.abspath(os.path.join('Models','Model_osp_5_85_18.h5'))

In [14]:
model_1 = load_model(model_1_path,compile=True)
model_2 = load_model(model_2_path,compile=True)
model_3 = load_model(model_3_path,compile=True)


---
# Model 1 Test on NORG Audio Dataset
---

In [18]:
print("Accuracy of our model on test data : " , model_1.evaluate(x_test,Y)[1]*100 , "%")
print("Accuracy of our model on test data : " , model_2.evaluate(x_test,Y)[1]*100 , "%")
print("Accuracy of our model on test data : " , model_3.evaluate(x_test,Y)[1]*100 , "%")

45/45 [==============================] - 1s 11ms/step - loss: 1.4143 - accuracy: 0.6319
Accuracy of our model on test data :  63.19444179534912 %
45/45 [==============================] - 0s 1ms/step - loss: 1.6352 - accuracy: 0.6097
Accuracy of our model on test data :  60.972219705581665 %
45/45 [==============================] - 0s 5ms/step - loss: 1.3796 - accuracy: 0.6313
Accuracy of our model on test data :  63.12500238418579 %


In [23]:
model_path = 'Models'
for m in os.listdir(model_path):
    model_no_path = os.path.abspath(os.path.join(model_path,m))
    model = load_model(model_no_path)
    print("-------------------------------------")
    print(f"Model Name : {m}")
    print(f"Accuracy of our model on test data :  {model.evaluate(x_test,Y)[1]*100 :.2f} %")
    print("-------------------------------------")
    print()

-------------------------------------
Model Name : Model_1.h5
45/45 [==============================] - 1s 9ms/step - loss: 1.9010 - accuracy: 0.5910
Accuracy of our model on test data :  59.10 %
-------------------------------------

-------------------------------------
Model Name : Model_2.h5
45/45 [==============================] - 1s 7ms/step - loss: 1.4559 - accuracy: 0.5250
Accuracy of our model on test data :  52.50 %
-------------------------------------

-------------------------------------
Model Name : Model_3.h5
45/45 [==============================] - 0s 4ms/step - loss: 1.9663 - accuracy: 0.5444
Accuracy of our model on test data :  54.44 %
-------------------------------------

-------------------------------------
Model Name : Model_osp.h5
45/45 [==============================] - 0s 6ms/step - loss: 1.3687 - accuracy: 0.5597
Accuracy of our model on test data :  55.97 %
-------------------------------------

-------------------------------------
Model Name : Model_osp_2